### ISSUE TITLE
I want to use on post processing stack v2 

### ISSUE THREAD

**Issue by handohuruuto** [yangrc1234/VolumeCloud#1]
I am sorry of I make a mistake since I cannot speak English veru well.

recently, post processing stack is version up.

so I cannot use this.
but I like this.

If you can, I would like you to be able to use.

**Comment by yangrc1234** [comment]
Post-processing stack in this repo is only used for the example scene, since the rendered result is in HDR, it needs to tone-map to look nice.
To use with post-processing v2, copy onoly the Assets/VolumeCloud folder to your project, and it should work with no problem.

**Comment by yangrc1234** [comment]
Also you should try other stuff to work with this thing(if you want something really nice), since this is only a simulation of low-altitude clouds. Maybe I'll update it one day lol.

**Comment by handohuruuto** [comment]
Thank you for your quick response!!!

However, as I told you to do Again the display is not done.

The version of unity uses 2018 2.0b9
Is it related?

I wanted to use a lightweight rendering pipeline
I am using this version.

**Comment by yangrc1234** [comment]
Sorry I'm not familiar with the new rendering pipeline stuff.
Maybe you could check Frame Debugger to see what happened.
Btw, since lightweight rendering pipeline aims for faster rendering, it's probably not a good idea to use heavy stuff like volume renderer this with it. And volume rendering is not supported on some mobile platforms(or most, I don't quite remember).
