### ISSUE TITLE
Compute shader for mobile

### ISSUE THREAD

**Issue by achestpro** [yangrc1234/VolumeCloud#5]
Beautiful clouds, amazing speed, everything is Hi-End. I wanted to see the speed on the mobile. It does not compile for android. Says that the compute shader is not supported by the platform. Maybe you know how to solve this problem?

**Comment by yangrc1234** [comment]
Thank you for your attention!  

I thought unity would just skip the compute shader asset if it's not supported by build target. If it stops you from building android target, just remove the compute shader asset inside VolumeCloud/Shaders.
The compute shader is only used when the option "Use hierarchical height map" on camera script is checked. So remember to uncheck it in your scene.

But I'm still not sure if it could run on Android, since many operations that are not very suited for mobile platform. 

Also I haven't tested opengl yet. So if you have any weird problems, post them here, I'll look into them later.
